//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FishingElite
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fish
    {
        public int id { get; set; }
        public string name { get; set; }
        public int count { get; set; }
        public string health { get; set; }
        public int active_id { get; set; }
    
        public virtual Active Active { get; set; }
    }
}
